name: hasala_saver
description: تطبيق إدارة الادخار (MVP) بالعربي وواجهة RTL
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  sqflite: ^2.3.3+1
  path: ^1.9.0
  intl: ^0.19.0
  shared_preferences: ^2.2.3
  flutter_local_notifications: ^17.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/